webleger.build.host=${webleger.build.host.prefered.protocol}://D:/git/WebLeger/WL_Website/website
#webleger.build.host=http://ethiknet.fr/webleger
webleger.build.host.prefered.protocol=file
webleger.minify.css.basename=${weblegerPom.minify.css.basename}
webleger.minify.jss.basename=${weblegerPom.minify.js.basename}

#template use to generate beaufity site (CSS, JS)
webleger.site.template=org_openCiLife_ecoWeb
#BackEnd template folder
webleger.site.template.backcend=${webleger.site.template}

webleger.components={"data":[{"file":"components/logHelper/logHelper.ftl"}, {"file":"components/commonHelper/commonHelper.ftl"}, {"file":"components/propertiesHelper/propertiesHelper.ftl"}, {"file":"components/includes/includes.ftl"}, {"file":"components/bootstrap3/bootstrap3.ftl"}, {"file":"${webleger.site.template.backcend}/custom/marcos.ftl"}, {"file":"components/hookHelper/hookHelper.ftl"}, {"file":"components/menu/menu.ftl"}, {"file":"components/block/block.ftl"}, {"file":"components/subcontent/subcontent.ftl"},{"file":"components/modal/modal.ftl"}, {"file":"components/form/form.ftl"}, {"file":"components/breadcrumb/breadcrumb.ftl"}, {"file":"components/sequenceHelper/sequenceHelper.ftl"}, {"file":"components/langHelper/langHelper.ftl"}, {"file":"components/ressourcesHelper/ressourcesHelper.ftl"}, {"file":"components/obfuscator/obfuscator.ftl"}, {"file":"components/action/action.ftl"}, {"file":"components/websiteCarbonBadge/websiteCarbonBadge.ftl"}, {"file":"components/sticker/sticker.ftl"}, {"file":"components/tableOfContent/tableOfContent.ftl"}, {"file":"components/fairlytics/fairlytics.ftl"}, {"file":"components/commonHelper/legal.ftl"}, {"file":"components/calendar/calendar.ftl"}, {"file":"components/glossary/glossary.ftl"}, {"file":"components/stripe/stripe.ftl"}, {"file":"components/map/map.ftl"}]}
webleger.hooks={"data":[]}
#permet de supprimer des fichiers ituitlisé (notament des "modeles" CSS (par exemple :templates/components/bootstrap3/aao-boostrap3-glyphicon.css,templates/components/bootstrap3/aar-bootstrap3-badge.css)
#webleger.remove.component.files=
#permet de supprimer des dossiers inutilsé (typiquement des composants), par exemple (templates/components/bootstrap3/copyToAssets/fonts,templates/components/carousel)
#webleger.remove.component.dirs=

webleger.assets.folder=assets

webleger.jvm.locale=fr_FR

webleger.site.langs.default=fr-FR
webleger.site.langs={"data":[{"local":"fr-FR", "title":"FR", "icon":"org_openCiLife_ecoWeb/images/lang/ico_fr.png", "folder":""}, {"local":"en-EN", "title":"EN", "icon":"org_openCiLife_ecoWeb/images/lang/ico_uk.png", "folder":"en"}]} 


webleger.site.header.title=WebLeger
webleger.site.header.description=WebLeger générateur de site éco-conçu
webleger.site.header.author=jDeruette
webleger.site.header.keyword=Web Eco-conception site-builder
webleger.site.header.iconShortcut=images/common/logo-small.png
webleger.site.header.robots=
#main site info (should be visible on any page on top of the page)
webleger.site.headline.tag=<h1 id="headerTitle">
webleger.site.headline.tag.end=</h1>
webleger.site.headline=WebLeger : générateur de site eco-conçu
webleger.site.logoLeft.file=images/common/logo_left.svg
webleger.site.logoLeft.description=Logo WebLeger
webleger.site.logoLeft.size.width.mobile=50px
webleger.site.logoLeft.size.width.desktop=200px
#webleger.site.logoRight.file=images/common/logo_right.png
#webleger.site.logoRight.description=Site Eco Conçu
webleger.site.logoRight.size.width.mobile=0
webleger.site.logoRight.size.width.desktop=0

webleger.site.script.header={"data":[]}
webleger.site.script.footer={"data":[]}

#menu configuration
webleger.site.menu.includeBlock=true
webleger.site.menu.tags.include=global
webleger.site.menu.includeCategories=${webleger.site.homepage.category}, ${webleger.site.imageHero.category}
webleger.site.menu.brand.src=
webleger.site.menu.brand.alt=${webleger.site.header.title}
webleger.site.menu.brand.specificClass=menu-logo

#HP and footer configuration
webleger.site.header.category=header
webleger.site.homepage.category=homepage
webleger.site.footer.category=footer

webleger.site.breakcrumb.display=true
webleger.site.breakcrumb.seprator=>>

#Dev configuration
webleger.site.debug.enabled=false

webleger.site.forulaire.contact.general.email=;jer___^^!????abaam
webleger.site.forulaire.contact.general.email.obfuscation-mask=@:!?,d:;,1:___,3:^^,4:u,9:5,gm:???,.co:aa,il:b
webleger.site.forulaire.contact.general.phone=tel3.33.50.jo.a2
webleger.site.forulaire.contact.general.phone.obfuscation-mask=0:tel,1:5,5:j,6:3,7:a,8:o
webleger.site.obfuscator.label=Cliquez pour afficher

webleger.site.body.class=
webleger.site.preheader.class=
webleger.site.header.class=
webleger.site.topContentContainer.class=primary
webleger.site.beforeMainContent.class=
webleger.site.mainContent.class=
webleger.site.beforePageHeader.class=primary
webleger.site.beforeBody.class=primary
webleger.site.afterBody.class=
webleger.site.footer.class=
webleger.site.afterFooter.class=

webleger.site.imageHero.image=
webleger.site.imageHero.category=

##### General legal informations
webleger.site.legal.enable=true
#legal name or person name
webleger.site.legal.identity.name=WebLeger (par EthikNet)
webleger.site.legal.identity.name.label=Nom
#optional. Exemple : SARL
webleger.site.legal.identity.status=
webleger.site.legal.identity.status.label=Statut
#optional. Exemple : 4 500\u20AC
webleger.site.legal.identity.capital_stock=
webleger.site.legal.identity.capital_stock.label=Captital
webleger.site.legal.contact.postal_address=
webleger.site.legal.contact.postal_address.label=Adresse
webleger.site.legal.contact.email=
webleger.site.legal.contact.email.label=E-mail
webleger.site.legal.contact.phone_number=<span data-obfuscatedkey="${webleger.site.forulaire.contact.general.phone.obfuscation-mask}" data-obfuscatedvalue="${webleger.site.forulaire.contact.general.phone}">Cliquez pour afficher</span>
webleger.site.legal.contact.phone_number.label=Téléphone
## Hosting
webleger.site.legal.hosting.name=EthikNet
webleger.site.legal.hosting.name.label=Nom de l'hébergeur
webleger.site.legal.hosting.company.name=EI DERUETTE Jérémie
webleger.site.legal.hosting.company.name.label=Nom de l'entreprise de l'hébergeur
webleger.site.legal.hosting.company.address=48 Montlambert 87160 CROMAC
webleger.site.legal.hosting.company.address.label=Adresse de l'hébergeur
webleger.site.legal.hosting.company.phone_number=<span data-obfuscatedkey="${webleger.site.forulaire.contact.general.phone.obfuscation-mask}" data-obfuscatedvalue="${webleger.site.forulaire.contact.general.phone}">Cliquez pour afficher</span>
webleger.site.legal.hosting.company.phone_number.label=Téléphonne de l'hébergeur
webleger.site.legal.hosting.company.email=<span data-obfuscatedkey="${webleger.site.forulaire.contact.general.email.obfuscation-mask}" data-obfuscatedvalue="${webleger.site.forulaire.contact.general.email}">Cliquez pour afficher</span>
webleger.site.legal.hosting.company.email.label=E-mail de l'hébergeur

##### specific legal informations
webleger.site.legal.identification1.type=Proposé par
webleger.site.legal.identification1.code=EI DERUETTE Jérémie  (EthikNet)
webleger.site.legal.identification2.type=
webleger.site.legal.identification2.code=
webleger.site.legal.identification3.type=
webleger.site.legal.identification3.code=
webleger.site.legal.identification4.type=
webleger.site.legal.identification4.code=
webleger.site.legal.identification5.type=
webleger.site.legal.identification5.code=
###for informational site only
#ethier"directeur" or "responsable de la rédaction"
webleger.site.legal.information.type=
webleger.site.legal.information.name=
##when required specific permission
webleger.site.legal.specific.permission.authority.name=
webleger.site.legal.specific.permission.authority.name.label=Nom de l'organisme
webleger.site.legal.specific.permission.authority.address=
webleger.site.legal.specific.permission.authority.address.label=Adresse de l'organisme
##for Regulated activities
# should be a link to a page
webleger.site.legal.specific.regulated_activities.rules=
webleger.site.legal.specific.regulated_activities.rules.label=Règles professionnelles applicables
webleger.site.legal.specific.regulated_activities.profesionnal_title=
webleger.site.legal.specific.regulated_activities.profesionnal_title.label=Titre professionnel
webleger.site.legal.specific.regulated_activities.allowed_contries=
webleger.site.legal.specific.regulated_activities.allowed_contries.label=État membre dans lequel a été octroyé le titre professionnel
webleger.site.legal.specific.regulated_activities.professional_order.name=
webleger.site.legal.specific.regulated_activities.professional_order.name.label=Nom de l'ordre ou de l'organisme professionnel

###for comercial site only
webleger.site.legal.cgv.category=cgv

#default style
webleger.site.style.font=trebuchet, helvetica, sans-serif
webleger.site.style.font.size=16px;
webleger.site.style.lineHeight=1.60;
webleger.site.style.color=hsl(150,50%,35%)
webleger.site.style.background.color=hsl(40,20%,97%)
webleger.site.style.disabled.background.color=grey
webleger.site.style.disabled.color=hsl(150,30%,15%)
webleger.site.style.highlight.background.color=${webleger.site.style.background.color}
webleger.site.style.highlight.color=hsl(150,50%,35%)
webleger.site.style.impact.color=${webleger.site.style.primary.background.color}
webleger.site.style.discret.background.color=lightgrey
webleger.site.style.discret.color=black
webleger.site.style.alternate.color=${webleger.site.style.primary.color}
webleger.site.style.alternate.background.color=${webleger.site.style.primary.background.color}
webleger.site.style.hr.color=${webleger.site.style.primary.background.color}
webleger.site.style.titles.color=${webleger.site.style.primary.background.color}
webleger.site.style.link.text-decoration=none
webleger.site.style.link.text-color=darkslategrey
webleger.site.style.link.text-color.visited=darkslategrey
webleger.site.style.link.text-color.hover=#690055
webleger.site.style.link.text-color.active=darkslategrey
webleger.site.style.muted.foreeground=hsl(0,0%,40%)

#primary colors
webleger.site.style.primary.color=${webleger.site.style.background.color}
webleger.site.style.primary.background.color=hsl(150,50%,35%)
webleger.site.style.primary.background.color.medium=${webleger.site.style.primary.background.color}
webleger.site.style.primary.background.color.light=${webleger.site.style.primary.background.color}
webleger.site.style.primary.disabled.background.color=grey
webleger.site.style.primary.disabled.color=black
webleger.site.style.primary.highlight.background.color=#4fc3f7
webleger.site.style.primary.highlight.color=${webleger.site.style.primary.background.color}
webleger.site.style.primary.impact.color=${webleger.site.style.primary.highlight.color}
webleger.site.style.primary.discret.background.color=WhiteSmoke
webleger.site.style.primary.discret.color=black
webleger.site.style.primary.alternate.color=${webleger.site.style.secondary.color}
webleger.site.style.primary.alternate.background.color=${webleger.site.style.secondary.background.color}
webleger.site.style.primary.hr.color=${webleger.site.style.secondary.background.color}
webleger.site.style.primary.titles.color=${webleger.site.style.primary.color}
webleger.site.style.primary.link.text-color=whitesmoke
webleger.site.style.primary.link.text-color.visited=black
webleger.site.style.primary.link.text-color.hover=white
webleger.site.style.primary.link.text-color.active=lightgrey
#secondary colors
webleger.site.style.secondary.color=${webleger.site.style.primary.background.color}
webleger.site.style.secondary.background.color=#EBE5D6
webleger.site.style.secondary.background.color.medium=${webleger.site.style.secondary.background.color}
webleger.site.style.secondary.background.color.light=${webleger.site.style.secondary.background.color}
webleger.site.style.secondary.disabled.background.color=grey
webleger.site.style.secondary.disabled.color=black
webleger.site.style.secondary.highlight.background.color=${webleger.site.style.primary.background.color}
webleger.site.style.secondary.highlight.color=#D6A63B
webleger.site.style.secondary.impact.color=${webleger.site.style.secondary.highlight.color}
webleger.site.style.secondary.discret.background.color=WhiteSmoke
webleger.site.style.secondary.discret.color=black
webleger.site.style.secondary.alternate.color=${webleger.site.style.secondary.color}
webleger.site.style.secondary.alternate.background.color=${webleger.site.style.background.color}
webleger.site.style.secondary.hr.color=${webleger.site.style.background.color}
webleger.site.style.secondary.titles.color=${webleger.site.style.secondary.color}
webleger.site.style.secondary.link.text-color=white
webleger.site.style.secondary.link.text-color.visited=grey
webleger.site.style.secondary.link.text-color.hover=white
webleger.site.style.secondary.link.text-color.active=lightgrey

#Go to https://fairlytics.tech/ to generate a key
webleger.component.fairlytics.key=2d146bb8413ff0a131ff71ac343c0170

#facebook
webleger.component.meta.dev.key=
webleger.component.meta.dev.sdk.version=v2.7
webleger.component.meta.facebook.container.url=https://www.facebook.com/{Your_company}/
webleger.component.meta.facebook.container.name={Your_company}
webleger.component.meta.facebook.container.width.mobile=300
webleger.component.meta.facebook.container.height.mobile=400
webleger.component.meta.facebook.container.width.desktop=500
webleger.component.meta.facebook.container.height.desktop=500

#Calendar
webleger.component.calendar.container.width.mobile=350
webleger.component.calendar.container.height.mobile=450
webleger.component.calendar.container.width.desktop=1200
webleger.component.calendar.container.height.desktop=600

webleger.component.glossary.terms={"data":[\
{"term":"en construction|en <em>construction|En cours de construction","def":"Ce site n'est pas encore fini !"}, \
{"term":"Site","def":"Une définition. (avec du <strong>gras</strong>) et une définition très longue <br> avec un retour à la ligne. <h3>et un titre (3) en HTML</h3> <br><br> un saut de ligne. <p>Un paragraphe (en html)</p>", "specificClassDef":"large"}\
]}
webleger.component.stripe.apiKey=Your_Stripe_API_KEY

#your custom global properties
webleger.site.ethikNetUrl=https://ethiknet.fr/ethiknet